# Generated by Django 3.0.5 on 2021-01-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('templ_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('temp_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('matchup_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='match_uploads/')),
                ('keyword', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='tvmatchup.Templates')),
            ],
        ),
    ]
