# Generated by Django 3.0.5 on 2021-01-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvmatchup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='templ_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
