# Generated by Django 3.0.5 on 2021-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvmatchup', '0002_auto_20210122_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='image',
            field=models.FileField(max_length=200, upload_to='media/'),
        ),
    ]
