# Generated by Django 3.0.5 on 2021-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvmatchup', '0005_auto_20210122_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='templ_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
