# Generated by Django 3.0.5 on 2021-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvmatchup', '0008_auto_20210122_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='templ_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
